name: Deploy To EC2

on: 
  push:
    branches:   
      - main

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name : SSH into EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: ./deploy.sh